type Product = {
    id: number
    title: string
    type: string
    price: number
    image: string
    category?: string
}

export const productsArrey: Product[] = [
    {
        id: 1,
        title: 'Curve',
        type: 'Chairs',
        price: 320.0,
        image: 'images/blog_pictures/curve_chair.jpeg',
        category: 'home',
    },
    {
        id: 2,
        title: 'Can',
        type: 'Sofas',
        price: 2100.0,
        image: 'images/blog_pictures/can_sofas.jpeg',
        category: 'home',
    },
    {
        id: 3,
        title: 'Belt',
        type: 'Armchairs',
        price: 680,
        image: 'images/blog_pictures/belt_armchairs.jpeg',
        category: 'home',
    },
    {
        id: 4,
        title: 'Giro LR',
        type: 'Tablets',
        price: 449,
        image: 'images/blog_pictures/giro-LR_tablets.jpeg',
        category: 'home',
    },
    {
        id: 5,
        title: 'Soft Edge',
        type: 'Chairs',
        price: 440,
        image: 'images/blog_pictures/soft_edge_chairs.jpeg',
        category: 'home',
    },
    {
        id: 6,
        title: 'Palissade',
        type: 'Sofas',
        price: 1890,
        image: 'images/blog_pictures/palissade_sofas.jpeg',
        category: 'home',
    },
    {
        id: 7,
        title: 'Bitta',
        type: 'Tablets',
        price: 1519,
        image: 'images/blog_pictures/bitta_tablets.jpeg',
        category: 'home',
    },
    {
        id: 8,
        title: 'Albert',
        type: 'Armchairs',
        price: 1600,
        image: 'images/blog_pictures/albert_armchairs.jpeg',
        category: 'home',
    },
    {
        id: 9,
        title: 'Navona',
        type: 'Sofas',
        price: 1669,
        image: 'images/blog_pictures/navova_sofas.jpeg',
        category: 'home',
    },
    {
        id: 10,
        title: 'Aruda',
        type: 'Tablets',
        price: 699,
        image: 'images/blog_pictures/aruda_tablets.jpeg',
        category: 'home',
    },

    {
        id: 11,
        title: 'Curve',
        type: 'Chairs',
        price: 320.0,
        image: 'images/blog_pictures/curve_chair.jpeg',
        category: 'chairs',
    },
    {
        id: 12,
        title: 'Revolt',
        type: 'Chairs',
        price: 275.0,
        image: 'images/blog_pictures/chair_revolt.jpg',
        category: 'chairs',
    },
    {
        id: 13,
        title: 'Avana',
        type: 'Chairs',
        price: 458.0,
        image: 'images/blog_pictures/chair_avana.jpg',
        category: 'chairs',
    },
    {
        id: 14,
        title: 'Ipanema',
        type: 'Chairs',
        price: 540.0,
        image: 'images/blog_pictures/chair_ipanema.jpg',
        category: 'chairs',
    },
    {
        id: 15,
        title: 'Result',
        type: 'Chairs',
        price: 279.0,
        image: 'images/blog_pictures/chair_result.jpg',
        category: 'chairs',
    },
    {
        id: 16,
        title: 'Henry',
        type: 'Tablets',
        price: 2091,
        image: 'images/blog_pictures/tables_henry.jpg',
        category: 'tablets',
    },
    {
        id: 17,
        title: 'Segmented',
        type: 'Tablets',
        price: 3200,
        image: 'images/blog_pictures/tablets_segmented.jpg',
        category: 'tablets',
    },
    {
        id: 18,
        title: 'Bitta',
        type: 'Tablets',
        price: 1519,
        image: 'images/blog_pictures/bitta_tablets.jpeg',
        category: 'tablets',
    },
    {
        id: 19,
        title: 'Meda Morph',
        type: 'Tablets',
        price: 350,
        image: 'images/blog_pictures/tablets_morth.jpg',
        category: 'tablets',
    },
    {
        id: 20,
        title: 'EM Table',
        type: 'Chairs',
        price: 1950.0,
        image: 'images/blog_pictures/tablets_tablet.jpg',
        category: 'tablets',
    },
    {
        id: 21,
        title: 'Twible',
        type: 'Sofas',
        price: 2800.0,
        image: 'images/blog_pictures/sofas_twible.jpg',
        category: 'sofas',
    },
    {
        id: 22,
        title: 'Angel',
        type: 'Sofas',
        price: 2100.0,
        image: 'images/blog_pictures/sofas_angel.jpg',
        category: 'sofas',
    },
    {
        id: 23,
        title: 'Polder',
        type: 'Sofas',
        price: 1876.0,
        image: 'images/blog_pictures/sofas_porder.jpg',
        category: 'sofas',
    },
    {
        id: 24,
        title: 'Navona',
        type: 'Sofas',
        price: 1669.0,
        image: 'images/blog_pictures/sofas_navona.jpg',
        category: 'sofas',
    },
    {
        id: 25,
        title: 'Fellini',
        type: 'Sofas',
        price: 2760.0,
        image: 'images/blog_pictures/sofas_fellini.jpg',
        category: 'sofas',
    },
    {
        id: 26,
        title: 'Quilt',
        type: 'Armchairs',
        price: 1259,
        image: 'images/blog_pictures/armchairs_quilt.jpg',
        category: 'armchairs',
    },
    {
        id: 27,
        title: 'Sendai',
        type: 'Armchairs',
        price: 679.0,
        image: 'images/blog_pictures/armchairs_sendai.jpg',
        category: 'armchairs',
    },
    {
        id: 28,
        title: 'Lima',
        type: 'Armchairs',
        price: 460.0,
        image: 'images/blog_pictures/armchairs_lima.jpg',
        category: 'armchairs',
    },
    {
        id: 29,
        title: 'Mercury',
        type: 'Armchairs',
        price: 1300,
        image: 'images/blog_pictures/armchairs_mercury.jpg',
        category: 'armchairs',
    },
    {
        id: 30,
        title: 'Daiki Studio',
        type: 'Armchairs',
        price: 1300,
        image: 'images/blog_pictures/armchairs_daiki.jpg',
        category: 'armchairs',
    },
]
